name = "GEOTRACESTools"
uuid = "01811018-0b43-45f6-bec3-119e05331aa1"
authors = ["Benoit Pasquier <pasquieb@uci.edu>"]
version = "0.1.0"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
